This is makeindex, version 2.15 [TeX Live 2010] (kpathsea + Thai support).
Scanning style file ./example.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file example.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (15 comparisons).
Generating output file example.acr....done (6 lines written, 0 warnings).
Output written in example.acr.
Transcript written in example.alg.
