This is makeindex, version 2.15 [TeX Live 2010] (kpathsea + Thai support).
Scanning style file ./glossaries-eg.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file glossaries-eg.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (15 comparisons).
Generating output file glossaries-eg.acr....done (6 lines written, 0 warnings).
Output written in glossaries-eg.acr.
Transcript written in glossaries-eg.alg.
